server:
  port: ${SERVER_PORT:8085}

spring:
  application:
    name: enrollment-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:55432}/${DB_NAME:campusenroll}}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USER:campus}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD:campus123}}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:${RABBITMQ_HOST:localhost}}
    port: ${SPRING_RABBITMQ_PORT:${RABBITMQ_PORT:5672}}
    username: ${SPRING_RABBITMQ_USERNAME:${RABBITMQ_USERNAME:campus}}
    password: ${SPRING_RABBITMQ_PASSWORD:${RABBITMQ_PASSWORD:campus123}}
    listener:
      simple:
        auto-startup: ${RABBITMQ_LISTENER_AUTO_STARTUP:true}

  jackson:
    serialization:
      write-dates-as-timestamps: false

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${ENROLLMENT_SHOW_SQL:false}
    properties:
      hibernate:
        "[format_sql]": true
        default_schema: campusenroll

campusenroll:
  services:
    student-base-url: ${STUDENT_SERVICE_URL:http://localhost:8081}
    course-base-url: ${COURSE_SERVICE_URL:http://localhost:8082}
    billing-base-url: ${BILLING_SERVICE_URL:http://localhost:8083}
    connect-timeout-ms: ${SERVICE_CONNECT_TIMEOUT_MS:3000}
    read-timeout-ms: ${SERVICE_READ_TIMEOUT_MS:5000}

  messaging:
    payments-exchange: campusenroll.payments
    dead-letter-exchange: campusenroll.dlx
    payment-approved-routing-key: payment.approved
    payment-failed-routing-key: payment.failed
    payment-approved-queue: enrollment.payment.approved
    payment-failed-queue: enrollment.payment.failed
    payment-approved-dlq: enrollment.payment.approved.dlq
    payment-failed-dlq: enrollment.payment.failed.dlq

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.hibernate.SQL: ${ENROLLMENT_HIBERNATE_SQL_LOG_LEVEL:WARN}
    org.hibernate.orm.jdbc.bind: ${ENROLLMENT_HIBERNATE_BIND_LOG_LEVEL:WARN}

